### PR TITLE
fix ruamel.yaml on 0.14.X for now

### PR DESCRIPTION
**Pull request by AvdN**
Thank you for using ruamel.yaml. 

There will be API changes in the 0.15+ versions, that might lead to warnings that 
your users could see. 
Therefore please release a version of your package with this change, so that it will not 
automatically take the latest ruamel.yaml release.

### CODE REVIEW

**Comment by 345thomas** [comment]
Thanks a bunch for not only the heads-up but even doing the PR, Anthon, much appreciated! ruamel is an awesome library, it's super useful and absolutely essential to the pypyr project. 

I gather from your docs that the updates on 0.15 might be unstable for a while. . . anything I can subscribe to for updates so I can know once you're happy enough w >0.15 for production use? I'm actually happy to switch over to 0.15 if it's just a matter of keeping up with api changes, but if you're going to embark on a bit more of an unstable anything-could-happen experimental phase I'll keep the dependency pinned until you say otherwise.

While we're here, I had actually been planning on giving ruamel a more prominent shout-out on the main README under the as-yet-unwritten thank yous. . . watch this space. . .

**Comment by AvdN** [comment]
Hi Thomas, 
at no point should there be functionality gone without an alternative interface. And removing will be preceded by several weeks of time in which there will be a warning that a change needs to be made. 

I looked at both your projects that use ruamel.yaml and you could already change to using the new interface e.g. depending on ruamel.yaml.version_info < (0, 15) keeping the old calls. That would do away with any problems with co-installed utilities requiring a particular version and you could float the version of ruamel.yaml for your packages once more.

**Comment by 345thomas** [comment]
Thanks for the roadmap Anthon, I'll flip over to 0.15 and re-float the dependency sometime in the coming week then. . .

**Comment by AvdN** [comment]
[Here](http://yaml.readthedocs.io/en/latest/api.html#transparent-usage-of-new-and-old-api) are some examples on how to be able to use the old and new API

**Comment by 345thomas** [comment]
sweet, thanks!

**Pull request merged**
